/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DarkModeToggle: typeof import('./components/DarkModeToggle.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    ErrorBoundary: typeof import('./components/ErrorBoundary.vue')['default']
    OfflineBanner: typeof import('./components/OfflineBanner.vue')['default']
    PipelineChart: typeof import('./components/PipelineChart.vue')['default']
    PipelineSummary: typeof import('./components/PipelineSummary.vue')['default']
    PipelineTable: typeof import('./components/PipelineTable.vue')['default']
    RowCountChart: typeof import('./components/RowCountChart.vue')['default']
    SummaryCard: typeof import('./components/SummaryCard.vue')['default']
    ToastHost: typeof import('./components/ToastHost.vue')['default']
  }
}
